- name: Copy Crystal runtime 2.0.3
  ansible.windows.win_copy:
    src: '\\my.azure.blob.storage.net\installmedia\Crystal\CrystalXIForElite.msi'
    dest: C:\temp
    remote_src: true
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_pass: "{{ ansible_password }}"

- name: Install Crystal runtime 2.0.3 omitting the product_id  
  ansible.windows.win_package:    
    path: 'C:\temp\CrystalXIForElite.msi'
    state: present
