---
- name: Create C:\temp directory if it doesn't exist
  ansible.windows.win_file:
    path: C:\temp
    state: directory
    
# - name: Create mapped drive with credentials and save the username and password
#   block:
#   - name: Save the network credentials required for the mapped drive
#     community.windows.win_credential:
#       name: runnerinstallmedia.file.core.windows.net
#       type: domain_password
#       username: 'localhost\my.azure.blob.storage.net'
#       secret: "{{ lookup('env','SA_PASSWORD') }}"
#       state: present

#   - name: Create a mapped drive that requires authentication
#     community.windows.win_mapped_drive:
#       letter: Z
#       path: \\my.azure.blob.storage.net\installmedia
#       state: present
#   vars:
#     # become is required to save and retrieve the credentials in the tasks
#     ansible_become: yes
#     ansible_become_method: runas
#     ansible_become_user: '{{ ansible_user }}'
#     ansible_become_pass: '{{ ansible_password }}'

- name: Change power plan to high performance
  community.windows.win_power_plan:
    name: high performance

- name: Redirect Timezone
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: fEnableTimeZoneRedirection
    data: 1
    type: dword
